blank_issues_enabled: false
contact_links:
  - name: Add location
    url: https://btcmap.org/add-location
    about: Please use the form on our website.
  - name: Report outdated information
    url: https://btcmap.org/report-outdated-info
    about: Please use the form on our website.
