name: Report outdated information
description: Merchant no longer accepts bitcoin or other data is incorrect.
labels: ["good first issue", "help wanted", "outdated info"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report! 
        Did you know you can update this data yourself on [OpenStreetMap](https://www.openstreetmap.org)? 
        Check out our [Wiki](https://github.com/teambtcmap/btcmap-data/wiki/Tagging-Instructions) for more intructions.
  - type: input
    id: location
    attributes:
      label: Merchant location
      description: URL can be found with the Share button on the location popup at btcmap.org/map
      placeholder: ex. https://btcmap.org/map?lat=69.3319548&long=88.2216992
    validations:
      required: true
  - type: textarea
    id: outdated
    attributes:
      label: Outdated information
      description: Provide what info is incorrect
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current information
      description: Provide the updated info on this location
    validations:
      required: true
  - type: textarea
    id: verify
    attributes:
      label: How did you verify this?
      description: Please provide additional info here
    validations:
      required: true
