name: Refresh data

on:
  schedule:
    - cron: '0 * * * *'
    
jobs:
  refresh-data:
    name: Refresh data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -X POST -d "@query.txt" -o data.json https://overpass-api.de/api/interpreter
      - uses: EndBug/add-and-commit@v9
        with:
          add: data.json
          default_author: github_actions
          message: 'Refresh data'
