name: Refresh data

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0,15,30,45 * * * *'
    
jobs:
  refresh-data:
    name: Refresh data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ./refresh-data.sh
      - uses: EndBug/add-and-commit@v9
        with:
          add: data.json
          default_author: github_actions
          message: 'Refresh data'
